services:
  db:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    container_name: web
    env_file:
      - ./.env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - db

  vue:
    container_name: vue-app
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  pgdata:
