worker_processes 1; 

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    
#    index path/to/file/index.html

    server {
        listen 8443 ssl;
        listen [::]:8443 ssl;
        root /var/www/html;
        server_name localhost;

        ssl_certificate /etc/ssl/certs/selfsigned.crt;
        ssl_certificate_key /etc/ssl/private/selfsigned.key;

        location / {
            try_files $uri $uri/ $uri.html /index.html;
        }

        location /api {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
