worker_processes 1;  # Nombre de processus de travail

events {
    worker_connections 1024;  # Nombre maximum de connexions par processus
}

http {
    include       mime.types;  # Inclut les types MIME
    default_type  application/octet-stream;  # Type par défaut

    sendfile        on;  # Active l'envoi de fichiers
    keepalive_timeout  65;  # Durée de vie de la connexion

    server {
        listen 80;  # Écoute sur le port 80 (HTTP)
        server_name localhost;

        # Redirection vers HTTPS
        return 301 https://$host:8443$request_uri;  # Redirige vers HTTPS sur le port 8443
    }

    server {
        listen 443 ssl;  # Écoute sur le port 443 (HTTPS)
        server_name localhost;

        ssl_certificate /etc/ssl/certs/selfsigned.crt;  # Chemin vers votre certificat
        ssl_certificate_key /etc/ssl/private/selfsigned.key;  # Chemin vers votre clé privée

        location / {
            proxy_pass http://vue-app:80;  # Redirige les requêtes vers l'application Vue
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api {
            proxy_pass http://web:8000;  # Redirige les requêtes vers l'API backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

