from base64 import b32encode;
from binascii import unhexlify;
from io import BytesIO;
from django.http import HttpResponse, JsonResponse;
from django.views.decorators.csrf import csrf_exempt;
from django.views.generic.base import View;
from django_otp.plugins.otp_totp.models import TOTPDevice;
from django_otp.util import random_hex;
from django.utils.module_loading import import_string;
from two_factor.utils import get_otpauth_url, totp_digits;
from django.contrib.sites.shortcuts import get_current_site;
from .serializers import QRCodeSerializer;
from django.contrib.auth import get_user_model;
from django.utils.decorators import method_decorator;
from django.views.decorators.csrf import csrf_exempt;
from django.core.exceptions import MultipleObjectsReturned;
from django.db.models import Count;
import qrcode;
import json;


# issues : 
#   1. user should only be able to create one QR Code to escape MultipleObjectsReturned exception

# User Model
User = get_user_model();

# Methods: ['GET', 'POST']
@method_decorator(csrf_exempt, name='dispatch')
class QRSetup(View):

    # endpoint: /get_qr_code/<std:user_id>
    # body: 
    # Note: 
    # qr code should be generated once and stored in the database
    def get(self, request, user_id, *args, **kwargs):
        default_qr_factory = "qrcode.image.svg.SvgPathImage";
        key = random_hex(20);
        print(f"key is: {key}");
        rawkey = unhexlify(key.encode('ascii'));
        b32key = b32encode(rawkey).decode("utf-8");

        # Get data for QRCode
        image_factory = import_string(default_qr_factory);
        content_type = "image/svg+xml; charset=utf-8";

        # fetch current user
        try:
            user = User.objects.get(public_id=user_id);
            username = user.username;
        except User.DoesNotExist:
            return JsonResponse({'error': 'User was not found!'}, status=404);

        issuer = get_current_site(self.request).name;
        otpauth_url = get_otpauth_url(
                accountname=username,
                issuer=issuer,
                secret=b32key,
                digits=totp_digits()
        );
        '''
        # Make the QR Code 
        img = qrcode.make(otpauth_url, image_factory=image_factory);
        resp = HttpResponse(content_type=content_type);
        img.save(resp); # return the image in svg format
        return resp;
    '''
        # Create the QR Code
        img = qrcode.make(otpauth_url, image_factory=image_factory);

        # Create a BytesIO object to save the image
        buffer = BytesIO();
        img.save(buffer);

        import base64;
        qr_code_data = base64.b64encode(buffer.getvalue()).decode();

        # Return JSON with the base64-encoded QR code and username
        return JsonResponse({
            'key': key,
            'issuer': issuer,
            'username': username,
            'qr_code': qr_code_data,
        });
    
    # endpoint: /save_qr_code/<std:user_id>
    # body: takes in key and its value in json
    # Note: it doesn't need any jwt token
    def post(self, request, user_id):

        # fetch current user
        try:
            user = User.objects.get(public_id=user_id);
            username = user.username;
        except User.DoesNotExist:
            return JsonResponse({'error': 'User was not found!'}, status=404);

        # create the table that will store the totp key for every user
        try:
            body = json.loads(request.body);
            self.key = body.get("key");
            if not self.key:
                return JsonResponse({'error': 'key is required'}, status=400);
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid Json provided'}, status=400);

        try:
            TOTPDevice.objects.create(
                user=user,
                key=self.key,
                tolerance=1,
                t0=0,
                step=30,
                drift=0,
                digits=6,
                name="default",
            );
            return JsonResponse({'message':'Opeartion was succesfful'}, status=201);
        except Exception as e:
            return JsonResponse({'message':'Opeartion has failed'}, status=400); 

@method_decorator(csrf_exempt, name='dispatch')
class VerifyOTPCode(View):
    # endpoint: /verify_otp_code/<std:user_id>
    # body: takes in key generated by scanning the auth application
    def post(self, request, user_id):
        # find the user with public_id = user_id
        try:
            user = User.objects.get(public_id=user_id);
            username = user.username;
        except User.DoesNotExist:
            return JsonResponse({'error': 'User was not found!'}, status=404);
        # retrieve the key from the database
        try:
            devices = TOTPDevice.objects.get(user=user);
            #otpauth_url = device.config_url
        except TOTPDevice.DoesNotExist:
            return JsonResponse({'error': f'TOTP Device was not found for user with email {user.username}'}, 
                                status=400);
        except MultipleObjectsReturned:
            return JsonResponse({'error': 'Multiple objects were found!'}, status=400);

        # cmp the keys and return response
        try:
            body = json.loads(request.body);
            user_otp_code = body.get("otp_code");
            if not user_otp_code:
                return JsonResponse({'error': 'otp code is required'}, status=400);
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid Json provided'}, status=400);

        if devices.verify_token(user_otp_code):
            return JsonResponse({'message': 'Access was granted'}, status=200);
        else:
            return JsonResponse({'error': 'Access was not granted'}, status=400);

