# Generated by Django 5.0.7 on 2024-09-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
    ]
