# Generated by Django 5.0.7 on 2024-09-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userqrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqrcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
