# Generated by Django 5.0.7 on 2024-09-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userqrcode_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQRCode',
        ),
    ]
