# Generated by Django 5.0.7 on 2024-10-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='A short bio about you.', max_length=500, null=True),
        ),
    ]
