# Generated by Django 5.0.7 on 2024-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/default_avatar.jpg', null=True, upload_to='media/avatars/'),
        ),
    ]
