# Generated by Django 5.0.7 on 2024-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='A short bio about you.', max_length=500, null=True),
        ),
    ]
