# Generated by Django 5.0.7 on 2024-10-08 11:55

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='match_history',
            field=models.ManyToManyField(blank=True, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('final_score', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=user.models.get_choices, max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_match_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
