# Generated by Django 5.0.7 on 2024-10-08 16:15

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_match_history_matchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', null=True, upload_to=user.models.upload_to),
        ),
    ]
